### PR TITLE
Fixed temporary #231 issue in eigenpy

### PR DESCRIPTION
**Pull request by cmastalli**
@wxmerkt -- perhaps we shouldn't merge this PR. However, if you have compile Crocoddyl (and its dependencies) with `march=native`, then you need to use this patch.

For more details about the issue in eigenpy, see my comment: https://github.com/stack-of-tasks/eigenpy/issues/231#issuecomment-844017263

### CODE REVIEW

**Comment by wxmerkt** [comment]
Let's wait for an upstream fix - there might be more issues with memory alignment we can then sort out here and in the controller interface (I am running all experiments without vectorisation since it won't work with the on-robot controller).

**Comment by cmastalli** [comment]
@wxmerkt --- this is a issue that still remains. And nobody is really working on it. Could we merge it?

**Comment by wxmerkt** [comment]
I wasn't aware that this is still an issue based on the upstream issue being closed. I'll go ahead and merge this to unblock work...

**Comment by cmastalli** [comment]
Thanks @wxmerkt :)

Btw, would you think it would be important to have a c++ class (with bindings) for the whole-body iface?

I have the impression that it would be very useful, and makes our demonstration safer

**Comment by wxmerkt** [comment]
I am seeing a very consistent 0.1-0.2ms for the Python version of `writeFromMessage` - do you see more or have seen issues in behaviour? I have a subscriber with bindings but that did not improve performance

**Pull request merged**
